setup schematiccolors set -wire #3ac0ff
setup schematiccolors set -graphic #00cc66
setup schematiccolors set -background #000000
setup schematiccolors set -selection #ffff00
setup schematiccolors set -minorgrid #c0c0c0
setup schematiccolors set -selectionbox #ffffff
setup schematiccolors set -portinstance #bf0000
setup schematiccolors set -portshape #ff01ff
setup schematiccolors set -porttext #ff01ff
setup schematiccolors set -netlabel #3ac0ff
setup schematiccolors set -textlabel #ff0100
setup schematiccolors set -cellname #00cc66
setup schematiccolors set -instancename #d9cc00
setup schematiccolors set -property #bfbfbf
setup schematiccolors set -hiddenproperty #7f7f7f
